[package]
name = "slackware-security-notifier"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.36.0", features = ["full"] }
serde = { version = "1.0.197", features = ["derive"] }
futures = "0.3.30"
reqwest = {version = "0.11.24", features = ["blocking", "multipart"] }
regex = "1.10.3"
watcher = "0.0.1"
tokio-cron-scheduler = "0.10.0"
chrono = { version = "0.4.34", features = ["unstable-locales"] }
twitter-v2 = "0.1.8"
env_logger = "0.11.2"
log = "0.4.20"


[dependencies.mongodb]
version = "2.8.1"
features = ["bson-chrono-0_4"]


